[package]
edition = "2021"
name = "clox-rs"
version = "0.1.0"

[dependencies]
derivative = "2.2.0"
num_enum = "0.5.7"
paste = "1.0.9"
shrinkwraprs = "0.3.0"

[features]
print_code = []
trace_execution = []
